import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import { chromium } from 'playwright'

const url = process.env.PROTOTYPE_URL || 'http://127.0.0.1:5174/'
const reviewDir = '../../.impeccable/review'
await fs.mkdir(reviewDir, { recursive: true })

const browser = await chromium.launch({
  headless: true,
  executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
})

try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce' })
  const page = await context.newPage()
  await page.goto(url, { waitUntil: 'networkidle' })
  await page.getByRole('heading', { name: 'Trucking', exact: true }).waitFor()
  assert.equal(await page.getByText('All shipments', { exact: true }).count(), 0)
  await page.locator('.MuiDataGrid-cell').filter({ hasText: /^Trucking$/ }).first().waitFor()
  assert.equal(await page.locator('.MuiDataGrid-cell').filter({ hasText: /^Land$/ }).count(), 0)
  await page.locator('.best-sidebar-shell:visible nav [role="button"]').filter({ hasText: 'Ocean' }).click()
  await page.getByRole('heading', { name: 'Ocean', exact: true }).waitFor()
  await page.locator('.best-sidebar-shell:visible nav [role="button"]').filter({ hasText: 'Air' }).click()
  await page.getByRole('heading', { name: 'Air', exact: true }).waitFor()
  await page.locator('.best-sidebar-shell:visible nav [role="button"]').filter({ hasText: 'Trucking' }).click()
  await page.getByRole('heading', { name: 'Trucking', exact: true }).waitFor()

  await page.locator('.best-sidebar-shell:visible nav [role="button"]').filter({ hasText: 'Quotations' }).click()
  await page.getByRole('heading', { name: 'Quotations', exact: true }).waitFor()
  const quotationHeaders = (await page.getByRole('columnheader').allTextContents()).map((label) => label.trim()).filter(Boolean)
  assert.equal(quotationHeaders[0], 'Quote Plan')
  assert.equal(quotationHeaders[1], 'Quote ID')
  assert.equal(quotationHeaders[2], 'Customer')
  assert.equal(quotationHeaders.includes('Created'), true)
  assert.equal(quotationHeaders.includes('Created Date'), false)
  assert.equal(quotationHeaders.includes('Expires'), false)
  assert.equal(quotationHeaders.includes('Rules'), false)
  assert.equal(await page.locator('.MuiDataGrid-row').count(), 4)
  await page.locator('.MuiDataGrid-row', { hasText: 'RATE-DEMO-001' }).click()
  await page.getByRole('heading', { name: '2026 Retail West LTL', exact: true }).waitFor()
  await page.getByText('Customer pricing contract').waitFor()
  await page.getByRole('heading', { name: 'Contract overview' }).waitFor()
  assert.equal(await page.locator('.rate-matrix-table [role="row"]').count(), 3)
  assert.equal(await page.locator('.surcharge-rule-table [role="row"]').count(), 3)
  await page.getByRole('button', { name: 'Add rule' }).click()
  await page.getByRole('combobox', { name: 'Additional rule 3 type' }).click()
  await page.getByRole('option', { name: 'Percentage surcharge' }).click()
  await page.getByLabel('Additional rule 3 name').fill('Weekend delivery')
  await page.getByLabel('Additional rule 3 applies when').fill('Delivery day is Saturday')
  await page.getByLabel('Additional rule 3 pricing').fill('8')
  await page.getByText('Weekend delivery', { exact: true }).waitFor()
  assert.equal(await page.locator('.surcharge-rule-table [role="row"]').count(), 4)
  await page.screenshot({ path: `${reviewDir}/pricing-rate-plan-desktop.png`, fullPage: true })

  await page.locator('.best-sidebar-shell:visible nav [role="button"]').filter({ hasText: 'Trucking' }).click()
  await page.getByRole('heading', { name: 'Trucking', exact: true }).waitFor()
  await page.locator('.MuiDataGrid-row', { hasText: 'TRK-DEMO-001' }).click()
  await page.getByRole('heading', { name: 'Commercial summary', exact: true }).waitFor()
  await page.getByText('2026 Retail West LTL · v2').waitFor()
  await page.getByRole('button', { name: 'Add adjustment' }).click()
  await page.getByLabel('Fee item').fill('Detention')
  await page.getByLabel('Amount (USD)').fill('125')
  await page.getByLabel('Reason and note').fill('Customer-approved wait time beyond the free period.')
  await page.getByRole('button', { name: 'Add adjustment', exact: true }).last().click()
  await page.getByText('Customer-approved wait time beyond the free period.').first().waitFor()
  await page.getByText('$725').first().waitFor()
  await page.getByRole('tab', { name: 'Vendor cost' }).click()
  await page.getByText('Pacific LTL Cost 2026 · v1').waitFor()
  await page.getByText('$470').first().waitFor()
  await page.getByRole('button', { name: 'Add adjustment' }).click()
  await page.getByLabel('Fee item').fill('Carrier detention')
  await page.getByLabel('Amount (USD)').fill('30')
  await page.getByLabel('Reason and note').fill('Approved carrier wait time.')
  await page.getByRole('button', { name: 'Add adjustment', exact: true }).last().click()
  await page.getByText('$500').first().waitFor()
  await page.getByText('$225').first().waitFor()
  await page.screenshot({ path: `${reviewDir}/pricing-shipment-desktop.png`, fullPage: true })

  const desktopFit = await page.evaluate(() => ({ viewport: innerWidth, document: document.documentElement.scrollWidth }))
  assert.ok(desktopFit.document <= desktopFit.viewport, `desktop horizontal overflow: ${JSON.stringify(desktopFit)}`)

  await page.locator('.best-sidebar-shell:visible nav [role="button"]').filter({ hasText: 'Billing' }).click()
  await page.getByRole('heading', { name: 'Billing & Accounting', exact: true }).waitFor()
  const billingHeaders = (await page.getByRole('columnheader').allTextContents()).map((label) => label.trim()).filter(Boolean)
  assert.equal(billingHeaders[0], 'Bill-to / Pay-to')
  assert.equal(billingHeaders.includes('Billing record'), false)
  assert.equal(billingHeaders.includes('Missing Data'), false)
  assert.equal(await page.getByText('Missing cost', { exact: true }).count(), 0)
  await page.screenshot({ path: `${reviewDir}/pricing-billing-list-desktop.png`, fullPage: true })
  await page.locator('.MuiDataGrid-row', { hasText: 'Demo Home Supply Inc.' }).click()
  await page.getByRole('heading', { name: 'Bill-to: Demo Home Supply Inc.', exact: true }).waitFor()
  await page.getByText('BILL-ACCT-001').waitFor()
  await page.getByText('Customer contract rate').waitFor()
  await page.getByRole('button', { name: 'Back to list' }).click()
  await page.locator('.MuiDataGrid-row', { hasText: 'Demo Carrier West LLC' }).click()
  await page.getByRole('heading', { name: 'Pay-to: Demo Carrier West LLC', exact: true }).waitFor()
  await page.getByText('PAY-ACCT-002').waitFor()
  await page.getByText('COST-DEMO-002').waitFor()
  await page.screenshot({ path: `${reviewDir}/pricing-billing-desktop.png`, fullPage: true })

  await page.locator('.best-sidebar-shell:visible nav [role="button"]').filter({ hasText: 'Partners' }).click()
  await page.getByRole('heading', { name: 'Partners', exact: true }).waitFor()
  await page.getByRole('tab', { name: /Customers/ }).waitFor()
  await page.getByText('Demo Retail Distribution LLC', { exact: true }).waitFor()
  assert.equal(await page.getByText('Pacific Linehaul LLC', { exact: true }).count(), 0)

  await page.getByRole('button', { name: 'Create', exact: true }).click()
  let partnerDialog = page.getByRole('dialog')
  await partnerDialog.getByRole('heading', { name: 'Create customer', exact: true }).waitFor()
  assert.equal(await partnerDialog.getByText('Type', { exact: true }).count(), 0)
  await partnerDialog.getByLabel('Customer name').fill('QA Customer')
  await partnerDialog.getByLabel('Primary contact').fill('Initial Contact')
  await partnerDialog.getByRole('button', { name: 'Create customer', exact: true }).click()
  await page.getByText('QA Customer', { exact: true }).waitFor()

  await page.locator('.MuiDataGrid-row', { hasText: 'QA Customer' }).click()
  partnerDialog = page.getByRole('dialog')
  await partnerDialog.getByRole('heading', { name: 'Edit customer', exact: true }).waitFor()
  await partnerDialog.getByLabel('Primary contact').fill('Updated Contact')
  await partnerDialog.getByRole('button', { name: 'Save changes', exact: true }).click()
  await page.getByText('Updated Contact', { exact: true }).waitFor()
  await page.getByLabel('QA Customer actions').click()
  await page.getByRole('menuitem', { name: 'Delete' }).click()
  await page.getByRole('heading', { name: 'Delete customer?', exact: true }).waitFor()
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  await page.getByText('QA Customer', { exact: true }).waitFor({ state: 'detached' })

  await page.getByRole('tab', { name: /Carriers/ }).click()
  await page.getByText('Pacific Linehaul LLC', { exact: true }).waitFor()
  assert.equal(await page.getByText('Demo Retail Distribution LLC', { exact: true }).count(), 0)

  await page.getByRole('button', { name: 'Create', exact: true }).click()
  partnerDialog = page.getByRole('dialog')
  await partnerDialog.getByRole('heading', { name: 'Create carrier', exact: true }).waitFor()
  assert.equal(await partnerDialog.getByText('Type', { exact: true }).count(), 0)
  await partnerDialog.getByLabel('Carrier name').fill('QA Carrier')
  await partnerDialog.getByLabel('Primary contact').fill('Dispatch Desk')
  await partnerDialog.getByRole('button', { name: 'Create carrier', exact: true }).click()
  await page.getByText('QA Carrier', { exact: true }).waitFor()
  await page.locator('.MuiDataGrid-row', { hasText: 'QA Carrier' }).click()
  partnerDialog = page.getByRole('dialog')
  await partnerDialog.getByRole('heading', { name: 'Edit carrier', exact: true }).waitFor()
  await partnerDialog.getByLabel('Primary contact').fill('Night Dispatch')
  await partnerDialog.getByRole('button', { name: 'Save changes', exact: true }).click()
  await page.getByText('Night Dispatch', { exact: true }).waitFor()
  await page.getByLabel('QA Carrier actions').click()
  await page.getByRole('menuitem', { name: 'Delete' }).click()
  await page.getByRole('heading', { name: 'Delete carrier?', exact: true }).waitFor()
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  await page.getByText('QA Carrier', { exact: true }).waitFor({ state: 'detached' })
  await page.screenshot({ path: `${reviewDir}/partners-carriers-desktop.png`, fullPage: true })
  await context.close()

  const mobileContext = await browser.newContext({ viewport: { width: 390, height: 844 }, reducedMotion: 'reduce' })
  const mobile = await mobileContext.newPage()
  await mobile.goto(url, { waitUntil: 'networkidle' })
  await mobile.getByRole('button', { name: 'Open navigation' }).click()
  await mobile.locator('.MuiDrawer-root .best-sidebar-shell nav [role="button"]').filter({ hasText: 'Quotations' }).click()
  await mobile.getByRole('heading', { name: 'Quotations', exact: true }).waitFor()
  await mobile.locator('.MuiDataGrid-row', { hasText: 'RATE-DEMO-004' }).click()
  await mobile.getByText('Customer pricing contract').waitFor()
  const mobileFit = await mobile.evaluate(() => ({ viewport: innerWidth, document: document.documentElement.scrollWidth }))
  assert.ok(mobileFit.document <= mobileFit.viewport, `mobile horizontal overflow: ${JSON.stringify(mobileFit)}`)
  await mobile.screenshot({ path: `${reviewDir}/pricing-rate-plan-mobile.png`, fullPage: true })
  await mobileContext.close()

  console.log(JSON.stringify({ functional: 'passed', desktopFit, mobileFit }, null, 2))
} finally {
  await browser.close()
}
